server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE #dynamic routing (used if multiple ports running)
          predicates:
            - Path=/product/**
        - id: CUSTOMER-SERVICE
          uri: http://localhost:9941/ #static routing
          predicates:
            - Path=/customer/**